from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QTableWidgetItem, QMessageBox
import pyodbc
from datetime import datetime

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1069, 720)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tableWidget_2 = QtWidgets.QTableWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_2.sizePolicy().hasHeightForWidth())
        self.tableWidget_2.setSizePolicy(sizePolicy)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(4)
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        self.verticalLayout_3.addWidget(self.tableWidget_2)
        self.gridLayout.addLayout(self.verticalLayout_3, 5, 0, 1, 3)
        self.lineEdit_stokkodu = QtWidgets.QLineEdit(Form)
        self.lineEdit_stokkodu.setObjectName("lineEdit_stokkodu")
        self.gridLayout.addWidget(self.lineEdit_stokkodu, 4, 0, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.dateEdit = QtWidgets.QDateEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dateEdit.sizePolicy().hasHeightForWidth())
        self.dateEdit.setSizePolicy(sizePolicy)
        self.dateEdit.setObjectName("dateEdit")
        self.verticalLayout_4.addWidget(self.dateEdit)
        self.gridLayout.addLayout(self.verticalLayout_4, 1, 1, 1, 1)
        self.pushButton_Ara = QtWidgets.QPushButton(Form)
        self.pushButton_Ara.setObjectName("pushButton_Ara")
        self.gridLayout.addWidget(self.pushButton_Ara, 4, 1, 1, 1)
        self.pushButton_hepsinikaydet = QtWidgets.QPushButton(Form)
        self.pushButton_hepsinikaydet.setObjectName("pushButton_hepsinikaydet")
        self.gridLayout.addWidget(self.pushButton_hepsinikaydet, 14, 2, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        self.verticalLayout.addWidget(self.tableWidget)
        self.gridLayout.addLayout(self.verticalLayout, 13, 0, 1, 3)
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 12, 0, 1, 1)
        self.lineEdit_miktar = QtWidgets.QLineEdit(Form)
        self.lineEdit_miktar.setObjectName("lineEdit_miktar")
        self.gridLayout.addWidget(self.lineEdit_miktar, 10, 0, 1, 1)
        self.pushButton_urunekle = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_urunekle.sizePolicy().hasHeightForWidth())
        self.pushButton_urunekle.setSizePolicy(sizePolicy)
        self.pushButton_urunekle.setObjectName("pushButton_urunekle")
        self.gridLayout.addWidget(self.pushButton_urunekle, 11, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.lineEdit_fisno = QtWidgets.QLineEdit(Form)
        self.lineEdit_fisno.setObjectName("lineEdit_fisno")
        self.gridLayout.addWidget(self.lineEdit_fisno, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 9, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

        # Set the current date in dateEdit with the format day/month/year
        self.dateEdit.setDisplayFormat("yyyy-MM-dd")
        self.dateEdit.setDate(QtCore.QDate.currentDate())

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Stok Kodu"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Stok Adı"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Birim"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Birim Fiyat"))
        self.pushButton_Ara.setText(_translate("Form", "Ara"))
        self.pushButton_hepsinikaydet.setText(_translate("Form", "Hepsini Kaydet"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Stok Kodu"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Stok Adı"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Birim"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Birim Fiyat"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Miktar"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Toplam Tutar"))
        self.label_9.setText(_translate("Form", "Eklenen Ürünler"))
        self.pushButton_urunekle.setText(_translate("Form", "Ürünü Ekle"))
        self.label_3.setText(_translate("Form", "Stok Kodu:"))
        self.label.setText(_translate("Form", "Fiş Numarası"))
        self.label_7.setText(_translate("Form", "Miktar"))